Prueba/Prueba/routes/web.php
<?php

/*
    Archivo de Rutas
*/
 use App\Http\Controllers;
use App\LoginControllers;


 

Route::resource('users', 'UserControllers');
 

Route::get('/', 'LoginControllers@login');
Route::get('/getlogin', 'LoginControllers@getlogin');
Route::get('/stop', 'LoginControllers@stop');

Prueba/Prueba/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

Prueba/Prueba/app/Http/Controllers/UserControllers.php
<?php

/*
  Controlador encargado de las acciones de los usuarios 
*/

namespace App\Http\Controllers;

use App\UsersModel;
use Illuminate\Http\Request;

class UserControllers extends Controller
{
     /*
          Metodo encargado de funciones del 
          index 
    */
    public function index()
    {
        $usuarios = UsersModel::getall();
        return view('layout/header').view('users/all' ,
            ['users' => $usuarios] ).view('layout/footer') ;
    }

     /*
          Metodo encargado de insertar un 
          nuevo usuario  
    */
    public function create()
    {
        return   view('layout/header').view('users/form').view('layout/footer');
    }
    
     /*
          Metodo encargado de listar 
          los registros provenientes
          de la Db
    */
    public function show()
    {
       $usuarios = UsersModel::getall();
        return view('layout/header').view('users/all' ,
            ['users' => $usuarios] ).view('layout/footer') ;
    }

     /*
          Metodo encargado de 
          llamar una funcion del modelo
          para eliminar un registro 
          de la DB 
    */
    public function destroy($id)
    {
        UsersModel:: de($id); 
        return redirect('users/show');
    }

     /*
          Metodo encargado de 
          llamar unas vista con datos
          traidos de la DB para su
          posterior modificacion
    */
    public function edit($id)
    {
        $usuario = UsersModel:: getid($id);
        return view('layout/header').view('users/edit' ,
            ['usuario' => $usuario] ).view('layout/footer') ;
        
    }
    /*
          Metodo encargado de 
          llamar una funcion del modelo
          para modificar un registro   
          de la DB
    */
    public function update($id)
    {
         $fecha = date('Y-m-d H:i:s', time()); 	
        
        $request= [
            'use_nam' =>$_POST['use_nam'],
            'use_doc'=>$_POST['use_doc'],
            'use_ema'=>$_POST['use_ema'],
            'use_pas'=>md5($_POST['use_pas']),
            'updated_at'=> $fecha ,
        ];
        UsersModel::up($request,$id);     
        return redirect('users/show');
        
    }
    
    /*
          Metodo encargado de 
          llamar una funcion del modelo
          para crear un nuevo registro   
          de la DB
    */
    public function store(Request $request)
    {
        $fecha = date('Y-m-d H:i:s', time()); 	
        $request= [
            'use_nam' =>$_POST['use_nam'],
            'use_doc'=>$_POST['use_doc'],
            'use_ema'=>$_POST['use_ema'],
            'use_pas'=>md5($_POST['use_pas']),
            'created_at'=> $fecha ,
        ];

        UsersModel::in($request);     
        return redirect('users/show');
    }


}

Prueba/Prueba/resources/views/users/all.blade.php
<br> <br>
        <h1 align="center"> Todos Los Usuarios  </h1>
        <hr>
        <a class="btn btn-info" href="{{route('users.create')}}"> Agregar Usuario </a>
        <br>

        <table class="table table-striped">
            <thead >    
            <tr>
                    
                    <th>Nombre </th>
                    <th>Email </th>
                    <th>Acciones </th>
                    
                </tr>
            <thead>    
                <?php foreach ($users as $row) { ?>
                 <tbody>   
                 <tr>
                    <td> <br> <?= $row->use_nam ?> </td>
                    <td> <br> <?= $row->use_ema ?> </td>
                    <td> 
                    <a class="btn btn-info" href="{{ route('users.edit',  $row->id )}}"><i class="glyphicon glyphicon-cog"> </i></a>
                    <br>  <br>
                    <form action=" {{ route('users.destroy', $row->id) }}" method="POST"> 
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger"  ><i class="glyphicon glyphicon-trash"> </i></button>
                      </form> 
                </td>
                </tr>
               <tbody> 
                <?php  }?>
        </table>
    </body>        
</html>    

Prueba/Prueba/resources/views/users/edit.blade.php
<br>

<?php foreach ($usuario as $row) { ?>

<div class="col-md-12">
    <br> <br>
        <h1 align="center"> Editar Usuario  </h1>
        <hr>

    <form method="POST" action="{{route('users.update', $row->id)}}">
    @csrf
    @method('PUT')
    <br>
     
<label> Nombre* </label>
<input type="text" class="form-control" value="{{$row->use_nam}}" name="use_nam" require>
<br>
<label> Documentos* </label>
<input type="text" class="form-control" value="{{$row->use_doc}}" name="use_doc" require>
<br>
<label> Email* </label>
<input type="email" class="form-control" value="{{$row->use_ema}}" name="use_ema" require >
<br>
<label> Contraseña* </label>
<input type="text" class="form-control" value=""   name="use_pas" require>
<br>
<button class="btn btn-info"> Enviar </button>
<form>
<?php } ?>
</div>

Prueba/Prueba/resources/views/users/form.blade.php
<br> <br> <br>
<div class="col-md-12">
    <br> <br>
        <h1 align="center"> Ingresar Los Usuario  </h1>
        <hr>
<form method="POST" action="{{route('users.store')}}">
    @csrf
<label> Nombre* </label>
<input type="text" class="form-control" name="use_nam" require>
<br>
<label> Documentos * </label>
<input type="text" class="form-control" name="use_doc" require>
<br>
<label> Email* </label>
<input type="email" class="form-control" name="use_ema" require >
<br>
<label> Contraseña* </label>
<input type="text" class="form-control" name="use_pas" require>
<br>
<button class="btn btn-info"> Enviar </button>
<form>
</div>    