Prueba/Prueba/routes/web.php
<?php

/*
    Archivo de Rutas
*/
 use App\Http\Controllers;
use App\LoginControllers;


 

Route::resource('users', 'UserControllers');
 

Route::get('/', 'LoginControllers@login');
Route::get('/getlogin', 'LoginControllers@getlogin');
Route::get('/stop', 'LoginControllers@stop');

Prueba/Prueba/resources/views/layout/footer.blade.php
<div class="col-md-12 barra" >
   
   <p align="center"> Todos los derechos reservados </p>  
   
</div>

<body>

<?php

/*
Archivo piede pagina
*/
?>    

Prueba/Prueba/resources/views/layout/header.blade.php
<?php

/*
 -Archivo padre de las vistas
 -Todo Pasa por esta session 
 -Modificando Siempre un solo archivo 
  en los menus
*/

@session_start(); 
if( $_SESSION["general"] == "false"){ 
      header('Location: /');
    exit;
}

?>

<style>
  .barra
  {
       background-color:darksalmon; 
       color:white;
        font-size:16px;
         font-family: cursive; 
         border-radius: 25px;

  }   
</style>

 
 
 
 <!DOCTYPE html>
<html>
<head>
     <link rel="stylesheet" type="text/css" href="{{asset('css/css/dist/css/bootstrap.css')}}"> 
	<title>Prueba</title>
</head>
<body style="backgroung-color:antiquewhite;" >
 
     <div class="col-md-12" >
     
          <div class="col-md-12 barra "  >
               <br>
          <div class="col-md-2"> <a href="{{route('users.index')}}" class="btn btn-info"> Inicio</a> 
                                 <a href="{{route('users.create')}}" class="btn btn-info">  Registrar </a>  
          </div>     
          <div class="col-md-2">  </div>  
          <div class="col-md-4">      </div>  
          <div class="col-md-1">      </div>  
          <div class="col-md-1">  </div>  
          <div class="col-md-1"> <a class="btn btn-info"  href="../stop"> Cerrar Session  </a> </div>  
          <br><br> 
          </div>